// Synced from web config for parity
export const CIVICS_RAW = [
  { q:"What is the supreme law of the land?", opts:["The Constitution","The Declaration of Independence","The Bill of Rights","Federal Law"], c:0 },
  { q:"What does the Constitution do?", opts:["Sets up the government","Declares war","Sets taxes","Appoints judges"], c:0 },
  { q:"The first three words of the Constitution are 'We the People.' What do they mean?", opts:["Self-governance / power from people","Trust in God","Unity of states","Freedom for all"], c:0 },
  { q:"What is an amendment?", opts:["A change or addition to the Constitution","A new law","A presidential order","A court ruling"], c:0 },
  { q:"What do we call the first ten amendments?", opts:["The Bill of Rights","The Declaration","The Articles","The Preamble"], c:0 },
  { q:"Name one right from the First Amendment.", opts:["Freedom of speech","Right to bear arms","Right to vote","Right to an attorney"], c:0 },
  { q:"How many amendments does the Constitution have?", opts:["27","10","21","33"], c:0 },
  { q:"What did the Declaration of Independence do?", opts:["Declared independence from Britain","Freed the slaves","Created the Constitution","Founded the government"], c:0 },
  { q:"What is the economic system of the United States?", opts:["Capitalist / free market","Socialist","Communist","Planned economy"], c:0 },
  { q:"What is the 'rule of law'?", opts:["Everyone must follow the law","The president is above the law","Judges make all laws","The military governs"], c:0 },
  { q:"Name one branch of government.", opts:["Legislative","Military","Police","Banking"], c:0 },
  { q:"What stops one branch from becoming too powerful?", opts:["Checks and balances","The Constitution alone","The President","The army"], c:0 },
  { q:"Who is in charge of the executive branch?", opts:["The President","Congress","The Supreme Court","The Governor"], c:0 },
  { q:"Who makes federal laws?", opts:["Congress","The President","The Supreme Court","Governors"], c:0 },
  { q:"What are the two parts of Congress?", opts:["The Senate and the House of Representatives","President and Vice President","Courts and Congress","Democrats and Republicans"], c:0 },
  { q:"How many U.S. Senators are there?", opts:["100","50","435","535"], c:0 },
  { q:"We elect a U.S. Senator for how many years?", opts:["6","4","2","8"], c:0 },
  { q:"How many voting members in the House of Representatives?", opts:["435","100","50","535"], c:0 },
  { q:"We elect a member of the House for how many years?", opts:["2","4","6","8"], c:0 },
  { q:"We elect a President for how many years?", opts:["4","6","2","8"], c:0 },
  { q:"In what month do we vote for President?", opts:["November","January","July","March"], c:0 },
  { q:"If the President can no longer serve, who becomes President?", opts:["The Vice President","The Speaker of the House","The Secretary of State","The Chief Justice"], c:0 },
  { q:"Who is the Commander in Chief of the military?", opts:["The President","The Secretary of Defense","The top General","The Vice President"], c:0 },
  { q:"Who signs bills to become laws?", opts:["The President","The Vice President","The Speaker","The Chief Justice"], c:0 },
  { q:"Who vetoes bills?", opts:["The President","Congress","The Supreme Court","The Governor"], c:0 },
  { q:"What does the President's Cabinet do?", opts:["Advises the President","Makes laws","Judges cases","Commands the army"], c:0 },
  { q:"What does the judicial branch do?", opts:["Reviews and explains laws","Makes laws","Enforces laws","Commands military"], c:0 },
  { q:"What is the highest court in the United States?", opts:["The Supreme Court","Federal Appeals Court","District Court","State Court"], c:0 },
  { q:"How many justices are on the Supreme Court?", opts:["9","12","7","11"], c:0 },
  { q:"What are the two major political parties?", opts:["Democratic and Republican","Liberal and Conservative","Green and Libertarian","Left and Right"], c:0 },
  { q:"Name one responsibility only for U.S. citizens.", opts:["Serve on a jury","Pay taxes","Obey laws","Work"], c:0 },
  { q:"What is the last day to send in federal tax forms?", opts:["April 15","January 1","July 4","December 31"], c:0 },
  { q:"At what age must males register for Selective Service?", opts:["18","21","16","25"], c:0 },
  { q:"What is one reason colonists came to America?", opts:["Freedom of religion","Gold rush","Trade with India","Escape the plague"], c:0 },
  { q:"Who lived in America before the Europeans arrived?", opts:["Native Americans","Africans","Asians","Nobody"], c:0 },
  { q:"What group was taken and sold as slaves?", opts:["Africans","Europeans","Asians","Native Americans"], c:0 },
  { q:"Why did the colonists fight the British?", opts:["Taxation without representation","Religion","Territory","Trade"], c:0 },
  { q:"Who wrote the Declaration of Independence?", opts:["Thomas Jefferson","George Washington","Benjamin Franklin","John Adams"], c:0 },
  { q:"When was the Declaration of Independence adopted?", opts:["July 4, 1776","July 4, 1789","January 1, 1800","September 17, 1787"], c:0 },
  { q:"What happened at the Constitutional Convention?", opts:["The Constitution was written","War was declared","Slaves were freed","President was elected"], c:0 },
  { q:"When was the Constitution written?", opts:["1787","1776","1800","1812"], c:0 },
  { q:"Who is the 'Father of Our Country'?", opts:["George Washington","Abraham Lincoln","Thomas Jefferson","John Adams"], c:0 },
  { q:"Who was the first President?", opts:["George Washington","John Adams","Thomas Jefferson","Benjamin Franklin"], c:0 },
  { q:"What territory did the U.S. buy from France in 1803?", opts:["Louisiana Territory","Alaska","Florida","California"], c:0 },
  { q:"Name one war fought by the U.S. in the 1800s.", opts:["Civil War","World War I","Revolutionary War","Vietnam War"], c:0 },
  { q:"Name one problem that led to the Civil War.", opts:["Slavery","Taxes","Territories","Immigration"], c:0 },
  { q:"What was one important thing Abraham Lincoln did?", opts:["Freed the slaves / saved the Union","Bought Louisiana","Wrote the Constitution","Was the first President"], c:0 },
  { q:"What did Susan B. Anthony do?", opts:["Fought for women's rights","Freed the slaves","Was the first female President","Wrote the Constitution"], c:0 },
  { q:"Name one war fought by the U.S. in the 1900s.", opts:["World War II","Civil War","Revolutionary War","War of 1812"], c:0 },
  { q:"Who was President during World War I?", opts:["Woodrow Wilson","Theodore Roosevelt","Franklin Roosevelt","Harry Truman"], c:0 },
  { q:"Who was President during the Great Depression and WWII?", opts:["Franklin Roosevelt","Harry Truman","Dwight Eisenhower","Herbert Hoover"], c:0 },
  { q:"Who did the U.S. fight in World War II?", opts:["Japan, Germany, and Italy","Russia, China, and Korea","Britain, France, Spain","Canada, Mexico, Cuba"], c:0 },
  { q:"What major event happened on September 11, 2001?", opts:["Terrorists attacked the United States","War in Iraq began","Hurricane Katrina","Financial crisis"], c:0 },
  { q:"What was the main concern during the Cold War?", opts:["Communism","Terrorism","Immigration","Economy"], c:0 },
  { q:"What movement tried to end racial discrimination?", opts:["Civil rights movement","Suffrage movement","Abolitionist movement","Progressive movement"], c:0 },
  { q:"What did Martin Luther King Jr. do?", opts:["Fought for civil rights","Was President","Wrote the Constitution","Commanded the army"], c:0 },
  { q:"Name one U.S. river.", opts:["Mississippi","Amazon","Nile","Danube"], c:0 },
  { q:"What ocean is on the East Coast?", opts:["Atlantic","Pacific","Indian","Arctic"], c:0 },
  { q:"What ocean is on the West Coast?", opts:["Pacific","Atlantic","Indian","Southern"], c:0 },
  { q:"Name one U.S. territory.", opts:["Puerto Rico","Cuba","Hawaii","Alaska"], c:0 },
  { q:"Name one state that borders Canada.", opts:["Montana","Texas","Florida","California"], c:0 },
  { q:"Name one state that borders Mexico.", opts:["Texas","Florida","Oregon","New York"], c:0 },
  { q:"What is the capital of the United States?", opts:["Washington, D.C.","New York City","Philadelphia","Boston"], c:0 },
  { q:"Where is the Statue of Liberty?", opts:["New York (Liberty Island)","Washington D.C.","Boston","Philadelphia"], c:0 },
  { q:"Why does the flag have 13 stripes?", opts:["They represent the 13 original colonies","13 presidents","13 wars","13 current states"], c:0 },
  { q:"Why does the flag have 50 stars?", opts:["One for each state","50 presidents","50 years","50 colonies"], c:0 },
  { q:"What is the name of the national anthem?", opts:["The Star-Spangled Banner","America the Beautiful","God Bless America","My Country 'Tis of Thee"], c:0 },
  { q:"When do we celebrate Independence Day?", opts:["July 4","March 4","December 25","January 1"], c:0 },
  { q:"Name one right from the Declaration of Independence.", opts:["Life, liberty, and pursuit of happiness","Right to own land","Right to free college","Right to hold office"], c:0 },
  { q:"What does freedom of religion mean?", opts:["You can practice any religion, or not practice one","Only one religion is allowed","You must attend church weekly","Religion is controlled by states"], c:0 },
  { q:"Who does a U.S. Senator represent?", opts:["All people of the state","Only voters in one district","Only members of one party","Only people in the capital city"], c:0 },
  { q:"Why do some states have more Representatives than others?", opts:["Because they have more people","Because they are older states","Because they pay more taxes","Because they are larger in land area"], c:0 },
  { q:"If both the President and the Vice President can no longer serve, who becomes President?", opts:["The Speaker of the House","The Chief Justice","The Secretary of State","The Senate Majority Leader"], c:0 },
  { q:"Name one right only for U.S. citizens.", opts:["Vote in a federal election","Freedom of speech","Freedom of religion","Freedom of assembly"], c:0 },
  { q:"What are two rights of everyone living in the United States?", opts:["Freedom of speech and freedom of religion","Right to vote and hold office","Right to a U.S. passport and jury duty","Right to bear arms and run for President"], c:0 },
  { q:"What do we show loyalty to when we say the Pledge of Allegiance?", opts:["The United States and the flag","A political party","The President only","A state government"], c:0 },
  { q:"What is one promise you make when you become a U.S. citizen?", opts:["Give up loyalty to other countries","Never travel outside the U.S.","Vote in every election","Serve in the military"], c:0 },
  { q:"How old do citizens have to be to vote for President?", opts:["18 and older","16 and older","21 and older","25 and older"], c:0 },
  { q:"Name one war fought by the United States in the 1700s.", opts:["The Revolutionary War","The Civil War","World War I","The Vietnam War"], c:0 },
  { q:"What was one important thing Benjamin Franklin did?", opts:["He was a U.S. diplomat","He was the first President","He wrote the Constitution alone","He led the Union Army"], c:0 },
  { q:"What did the Federalist Papers support?", opts:["The passage of the U.S. Constitution","The end of slavery","The Louisiana Purchase","The Declaration of Independence"], c:0 },
  { q:"Name one writer of the Federalist Papers.", opts:["James Madison","George Washington","Abraham Lincoln","Thomas Paine"], c:0 },
  { q:"What war was fought between the North and the South?", opts:["The Civil War","The Revolutionary War","World War II","The Korean War"], c:0 },
  { q:"What did the Emancipation Proclamation do?", opts:["Freed slaves in the Confederacy","Ended World War I","Created the Constitution","Gave women the right to vote"], c:0 },
  { q:"Before he was President, Eisenhower was a general. What war was he in?", opts:["World War II","World War I","The Civil War","The War of 1812"], c:0 },
  { q:"Before he was President, what did Barack Obama do?", opts:["U.S. Senator","Supreme Court Justice","Governor of New York","Secretary of State"], c:0 },
  { q:"Name one of the two longest rivers in the United States.", opts:["Missouri River","Colorado River","Hudson River","Rio Grande"], c:0 },
  { q:"Name one American Indian tribe in the United States.", opts:["Cherokee","Viking","Inca","Saxon"], c:0 },
  { q:"Name one U.S. state that does not have an ocean coastline.", opts:["Nevada","California","Florida","New York"], c:0 },
  { q:"Name one national U.S. holiday.", opts:["Thanksgiving","Earth Day","Halloween","Valentine's Day"], c:0 },
  { q:"When is Memorial Day celebrated in the United States?", opts:["The last Monday in May","July 4","The first Monday in September","November 11"], c:0 },
  { q:"When is Labor Day celebrated in the United States?", opts:["The first Monday in September","The last Monday in May","July 4","December 25"], c:0 },
  { q:"When is Constitution Day?", opts:["September 17","July 4","June 14","November 11"], c:0 },
  { q:"What is one power of the federal government?", opts:["To print money","To issue driver licenses","To run local schools","To create city laws"], c:0 },
  { q:"What is one power of the states?", opts:["Provide schooling and education","Print money","Declare war","Create treaties"], c:0 },
  { q:"Name one Cabinet-level position.", opts:["Secretary of State","Chief Justice","Speaker of the House","Senate President"], c:0 },
  { q:"What is one responsibility that is for all people in the United States?", opts:["Obey the law","Vote in federal elections","Serve on a jury for federal court","Run for office"], c:0 },
  { q:"When is Flag Day?", opts:["June 14","July 4","September 17","November 11"], c:0 },
  { q:"What is one way Americans can participate in democracy?", opts:["Vote in elections","Ignore public issues","Skip taxes","Refuse jury service"], c:0 },
  { q:"Where can freedom of speech be used legally in daily life?", opts:["Public discussion and peaceful expression","Only at home","Only in court","Only in schools"], c:0 },
];

export function shuffleTest(questions) {
  const shuffled = questions.map(q => {
    const indices = q.opts.map((_, i) => i);
    for (let i = indices.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [indices[i], indices[j]] = [indices[j], indices[i]]; }
    return { q: q.q, opts: indices.map(i => q.opts[i]), correctIdx: indices.indexOf(q.c) };
  });
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}
